## Dinámica del modelo

En el contexto del fútbol llamamos *jugada* a una sucesión de acciones donde el balón se traslada desde un punto inicial donde el equipo A tiene el balón hasta un punto final que puede ser: perder el balón, tirar a puerta y no anotar gol o tirar y anotar gol.

*Ejemplo: El balón comienza en el saque de meta del portero, el portero da un pase a un defensa que se encuentra en el primer tercio, que esté da un pase a un delantero que se encuentra en el tercer tercio y al intentar un regate pierde el balón.*

En nuestro contexto se verá como el hecho de iniciar la sucesión de acciones desde alguna sección $C_i$ y terminar en alguno de los 3 estados absorbentes. 

*Ejemplo* 
$$
C_1\xrightarrow{p}C_1\xrightarrow{p}C_3\xrightarrow{r}L_p.
$$

```{python}
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt 
from mplsoccer import Pitch, FontManager, add_image

pitch = Pitch(line_color='black',linewidth=1)
fig, ax = pitch.draw()
pitch.lines(40,0,40,80,color = 'gray', linewidth = 1, ax=ax, linestyle = '--')

pitch.lines(80,0,80,80,color = 'gray', linewidth = 1, ax=ax, linestyle = '--')

pitch.annotate(text='$C_1$',xytext=(10,10),xy=(84,45),ax=ax)
pitch.annotate(text='$C_2$',xytext=(50,10),xy=(84,45),ax=ax)
pitch.annotate(text='$C_3$',xytext=(90,10),xy=(84,45),ax=ax)

pitch.scatter(0,40, color = 'red', ax=ax)
pitch.scatter(24,62,color = 'red',ax=ax)
pitch.scatter(84,45,color = 'red',ax=ax)

pitch.arrows(0,40,24,62,color = 'green', width = 2,label = 'Pase', ax=ax)
pitch.arrows(24,62,84,45,color = 'green', width = 2, ax=ax)
pitch.arrows(84,45,88,46,color = 'blue', width = 2,label = 'Regate', ax=ax)
pitch.annotate(text='$L_p$',xytext=(89,47),xy=(84,45),ax=ax)

ax.legend(shadow=True, loc = 'upper left', ncol=2, facecolor = 'white', edgecolor = 'None')

plt.show()
```

Para movernos de un estado $S_i$ a un estado $S_j$ mediante una acción $a_k$ haremos uso de las probabilidades de transición, estas probabilidades las estimaremos utilizando datos extraídos de [FBREF](https://fbref.com/es/) para 4 clubes: [Chivas](https://fbref.com/es/equipos/c02b0f7a/2023-2024/Estadisticas-de-Guadalajara), [América](https://fbref.com/es/equipos/18d3c3a3/2023-2024/Estadisticas-de-America), [Cruz Azul](https://fbref.com/es/equipos/632f1838/2023-2024/Estadisticas-de-Cruz-Azul) y [Pumas](https://fbref.com/es/equipos/c9d59c6c/2023-2024/Estadisticas-de-Pumas-UNAM) de la temporada 2023-2024

Primero vamos a interpretar las probabilidades de transición con la finalidad de descartar aquellas transciones que no serán posibles con nuestro modelo y con la naturaleza de un partido.

-   Fijamos el estado $C_1$.

    -   Consideramos la acción $p$:

        $P(C_1,p,C_1)=$ La probabilidad de estar en la zona $C_1$ dar un *pase* y terminar en la zona $C_1$.

        $P(C_1,p,C_2)=$ La probabilidad de estar en la zona $C_1$ dar un *pase* y terminar en la zona $C_2$.

        $P(C_1,p,C_3)=$ La probabilidad de estar en la zona $C_1$ dar un *pase* y terminar en la zona $C_3$.

        $P(C_1,p,L_p)=$ La probabilidad de estar en la zona $C_1$ dar un *pase* y perder el balón.

        $P(C_1,p,nG)=$ La probabilidad de estar en la zona $C_1$ dar un *pase* y no anotar gol.

        $P(C_1,p,G)=$ La probabilidad de estar en la zona $C_1$ dar un *pase* y anotar gol.

        De esta lista de probabilidades para la acción $p$ notemos que $P(C_1,p,nG)=P(C_1,p,G)=0$ esto pues la única acción admisible para terminar en los estados $\{nG,G\}$ es $t$.

    -   Consideramos la acción $r$:

        $P(C_1,r,C_1)=$ La probabilidad de estar en la zona $C_1$ hacer un *regate* y terminar en la zona $C_1$.

        $P(C_1,r,C_2)=$ La probabilidad de estar en la zona $C_1$ hacer un *regate* y terminar en la zona $C_2$.

        $P(C_1,r,C_3)=$ La probabilidad de estar en la zona $C_1$ hacer un *regate* y terminar en la zona $C_3$.

        $P(C_1,r,L_p)=$ La probabilidad de estar en la zona $C_1$ hacer un *regate* y perder el balón.

        $P(C_1,r,nG)=$ La probabilidad de estar en la zona $C_1$ hacer un *regate* y no anotar gol.

        $P(C_1,r,G)=$ La probabilidad de estar en la zona $C_1$ hacer un *regate* y anotar gol.

        De esta lista de probabilidades para la acción $r$ notemos que $P(C_1,r,nG)=P(C_1,r,nG)=0$ esto pues la única acción admisible para terminar en los estados $nG,G$ es $t$.

        Además $P(C_1,r,C_3)=0$, pues al realizar un *regate* solo tenemos dos opciones:

        nos mantenemos en la zona $C_1$ o avanzamos a la zona siguiente $C_2$.

    -   Consideramos la acción $t$:

        En este caso tendremos que $P(C_1,t,C_1)=P(C_1,t,C_2)=P(C_1,t,C_3)=P(C_1,t,L_p)=0$ pues después de realizar un *tiro* solo tendremos dos estados posibles $\{nG,G\}$.

        $P(C_1,t,nG)=$ La probabilidad de estar en la zona $C_1$ hacer un *tiro* y no anotar gol.

        $P(C_1,t,G)=$ La probabilidad de estar en la zona $C_1$ hacer un *tiro* y anotar gol.

        Sin embargo, como suponemos que las acciones que toman las futbolistas son coherentes, no tiene sentido realizar un *tiro* desde la zona $C_1$, pues la distancia hacia la porteria contaría es muy lejana y la probabilidad de anotar un gol es prácticamente nula. Por tanto

        $$
          P(C_1,t,S)=0,\hspace{0.5cm}\forall S\in \mathcal{S}.
          $$

-   Fijamos el estado $C_2$.

    -   Consideramos la acción $p$:

        $P(C_2,p,C_1)=$ La probabilidad de estar en la zona $C_2$ dar un *pase* y terminar en la zona $C_1$.

        $P(C_2,p,C_2)=$ La probabilidad de estar en la zona $C_2$ dar un *pase* y terminar en la zona $C_2$.

        $P(C_2,p,C_3)=$ La probabilidad de estar en la zona $C_2$ dar un *pase* y terminar en la zona $C_3$.

        $P(C_2,p,L_p)=$ La probabilidad de estar en la zona $C_2$ dar un *pase* y perder el balón.

        $P(C_2,p,nG)=$ La probabilidad de estar en la zona $C_2$ dar un *pase* y no tirar a gol.

        $P(C_2,p,G)=$ La probabilidad de estar en la zona $C_2$ dar un *pase* y terminar en gol.

        De esta lista de probabilidades para la acción $p$ notemos que $P(C_2,p,nG)=P(C_2,p,nG)=0$ esto pues la única acción admisible para terminar en los estados $\{nG,G\}$ es $t$.

    -   Consideramos la acción $r$:

        $P(C_2,r,C_1)=$ La probabilidad de estar en la zona $C_2$ hacer un *regate* y terminar en la zona $C_1$.

        $P(C_2,r,C_2)=$ La probabilidad de estar en la zona $C_2$ hacer un *regate* y terminar en la zona $C_2$.

        $P(C_2,r,C_3)=$ La probabilidad de estar en la zona $C_2$ hacer un *regate* y terminar en la zona $C_3$.

        $P(C_2,r,L_p)=$ La probabilidad de estar en la zona $C_2$ hacer un *regate* y perder el balón.

        $P(C_2,r,nG)=$ La probabilidad de estar en la zona $C_2$ hacer un *regate* y no anotar gol.

        $P(C_2,r,G)=$ La probabilidad de estar en la zona $C_2$ hacer un *regate* y anotar gol.

        De esta lista de probabilidades para la acción $r$ notemos que $P(C_2,r,nG)=P(C_2,r,G)=0$ esto pues la única acción admisible para terminar en los estados $\{nG,G\}$ es $t$.

    -   Consideramos la acción $t$:

        En este caso tendremos que $P(C_2,t,C_1)=P(C_2,t,C_2)=P(C_2,t,C_3)=P(C_2,t,L_p)=0$ pues después de realizar un *tiro* solo tendremos dos estados posibles $\{nG,G\}$.

        $P(C_2,t,nG)=$ La probabilidad de estar en la zona $C_2$ hacer un *tiro* y no anotar gol.

        $P(C_2,t,G)=$ La probabilidad de estar en la zona $C_2$ hacer un *tiro* y anotar gol.

-   Fijamos el estado $C_3$

    -   Consideramos la acción $p$:

        $P(C_3,p,C_1)=$ La probabilidad de estar en la zona $C_3$ dar un *pase* y terminar en la zona $C_1$.

        $P(C_3,p,C_2)=$ La probabilidad de estar en la zona $C_3$ dar un *pase* y terminar en la zona $C_2$.

        $P(C_3,p,C_3)=$ La probabilidad de estar en la zona $C_3$ dar un *pase* y terminar en la zona $C_3$.

        $P(C_3,p,L_p)=$ La probabilidad de estar en la zona $C_3$ dar un *pase* y perder el balón.

        $P(C_3,p,nG)=$ La probabilidad de estar en la zona $C_3$ dar un *pase* y no tirar a gol.

        $P(C_3,p,G)=$ La probabilidad de estar en la zona $C_3$ dar un *pase* y terminar en gol.

        De esta lista de probabilidades para la acción $p$ notemos que $P(C_3,p,nG)=P(C_2,p,G)=0$ esto pues la única acción admisible para terminar en los estados $\{nG,G\}$ es $t$.

    -   Consideramos la acción $r$:

        $P(C_3,r,C_1)=$ La probabilidad de estar en la zona $C_3$ hacer un *regate* y terminar en la zona $C_1$.

        $P(C_3,r,C_2)=$ La probabilidad de estar en la zona $C_3$ hacer un *regate* y terminar en la zona $C_2$.

        $P(C_3,r,C_3)=$ La probabilidad de estar en la zona $C_3$ hacer un *regate* y terminar en la zona $C_3$.

        $P(C_3,r,L_p)=$ La probabilidad de estar en la zona $C_3$ hacer un *regate* y perder el balón.

        $P(C_3,r,nG)=$ La probabilidad de estar en la zona $C_3$ hacer un *regate* y no anotar gol.

        $P(C_3,r,G)=$ La probabilidad de estar en la zona $C_3$ hacer un *regate* y anotar gol.

        De esta lista de probabilidades para la acción $r$ notemos que $P(C_3,r,nG)=P(C_3,r,G)=0$ esto pues la única acción admisible para terminar en los estados $\{nG,G\}$ es $t$.

        Además $P(C_3,r,C_1)=0$, pues al realizar un *regate* solo tenemos dos opciones o nos mantenemos en la zona $C_3$ o retrocedemos a la zona anterior $C_2$.

    -   Consideramos la acción $t$:

        En este caso tendremos que $P(C_3,t,C_1)=P(C_3,t,C_2)=P(C_3,t,C_3)=P(C_3,t,L_p)=0$ pues después de realizar un *tiro* solo tendremos dos estados posibles $\{nG,G\}$.

        $P(C_3,t,nG)=$ La probabilidad de estar en la zona $C_3$ hacer un *tiro* y no anotar gol.

        $P(C_3,t,G)=$ La probabilidad de estar en la zona $C_3$ hacer un *tiro* y anotar gol.

-   Por último como $\{L_p,nG,G\}$ son estados absorbentes, entonces $\forall a\in\mathcal{A}.$

$$
    P(L_p,a,S)=\left\{\begin{array}{ccc}
            1 & \text{si} & S = L_p\\
            0 & o.c. &
            \end{array}\right. 
$$

$$
    P(nG,a,S)=\left\{\begin{array}{ccc}
            1 & \text{si} & S = nG\\
            0 & o.c. &
            \end{array}\right. 
$$

$$
    P(G,a,S)=\left\{\begin{array}{ccc}
            1 & \text{si} & S = G\\
            0 & o.c. &
            \end{array}\right. 
$$

Para facilitar las estimaciones se renombrarán cada probabiidad con los parámetros que se muestran en las siguientes tablas

| Probabilidades | Parámetros    |
|----------------|---------------|
| $P(C_1,p,C_1)$ | $\alpha_{1p}$ |
| $P(C_1,p,C_2)$ | $\alpha_{2p}$ |
| $P(C_1,p,C_3)$ | $\alpha_{3p}$ |
| $P(C_1,p,L_p)$ | $\alpha_{4p}$ |
| $P(C_1,r,C_1)$ | $\alpha_{1r}$ |
| $P(C_1,r,C_2)$ | $\alpha_{2r}$ |
| $P(C_1,r,L_p)$ | $\alpha_{3r}$ |

: Parámetros para las probabilidades de $C_1$

| Probabilidades | Parámetros   |
|----------------|--------------|
| $P(C_2,p,C_1)$ | $\beta_{1p}$ |
| $P(C_2,p,C_2)$ | $\beta_{2p}$ |
| $P(C_2,p,C_3)$ | $\beta_{3p}$ |
| $P(C_2,p,L_p)$ | $\beta_{4p}$ |
| $P(C_2,r,C_1)$ | $\beta_{1r}$ |
| $P(C_2,r,C_2)$ | $\beta_{2r}$ |
| $P(C_2,r,C_3)$ | $\beta_{3r}$ |
| $P(C_2,r,L_p)$ | $\beta_{4r}$ |
| $P(C_2,t,nG)$  | $\beta_{1t}$ |
| $P(C_2,t,G)$   | $\beta_{1t}$ |

: Parámetros para las probabilidades de $C_2$

| Probabilidades | Parámetros    |
|----------------|---------------|
| $P(C_3,p,C_1)$ | $\gamma_{1p}$ |
| $P(C_3,p,C_2)$ | $\gamma_{2p}$ |
| $P(C_3,p,C_3)$ | $\gamma_{3p}$ |
| $P(C_3,p,L_p)$ | $\gamma_{4p}$ |
| $P(C_3,r,C_2)$ | $\gamma_{1r}$ |
| $P(C_3,r,C_3)$ | $\gamma_{2r}$ |
| $P(C_3,r,L_p)$ | $\gamma_{3r}$ |
| $P(C_3,t,nG)$  | $\gamma_{1t}$ |
| $P(C_3,t,G)$   | $\gamma_{2t}$ |

: Parámetros para las probabilidades de $C_3$